version: '3'
services:
  gateway:
    image: coinform/gateway:latest
    depends_on:
      - redis
    ports:
      - "8080:8080"
    deploy:
      replicas: 1
  redis:
    image: redis
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    deploy:
      placement:
        constraints: [node.role == manager]